CREATE DATABASE IF NOT EXISTS ai;

USE ai;

CREATE TABLE IF NOT EXISTS Accounts(
    AccountID INT NOT NULL AUTO_INCREMENT,
    AccountName VARCHAR(128) NOT NULL,
    Premium BIT DEFAULT FALSE,
    PRIMARY KEY (AccountID)
);

CREATE TABLE IF NOT EXISTS LMs(
    LMID INT NOT NULL AUTO_INCREMENT,
    AccountID INT NOT NULL,
    LMName VARCHAR(128) NOT NULL,
    NeedsPremium BIT DEFAULT TRUE,
    PRIMARY KEY (LMID),
    FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID)
);

INSERT INTO Accounts(AccountName)
VALUES ("Andersen Job"), ("Andrew Smith");

INSERT INTO LMs(AccountID, LMName)
VALUES (1, "chatGPT");