FROM xela10001/ai-text-detector:communicator
ENV PYTHONBUFFERED=1
ARG LM_NAME
COPY ./LMs/${LM_NAME}/lm_submission.py ./
COPY ./LMs/${LM_NAME}/requirements.txt ./
COPY ./communicator.py ./
COPY ./messages.py ./