version: "3.9"

services:

  db:
    build: ./mysql
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/data.sql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ai
      MYSQL_USER: non_root
      MYSQL_PASSWORD: ai

  api:
    build: ./django
    volumes:
      - ../DjangoAPI:/DjangoAPI
    working_dir: /DjangoAPI
    ports:
      - "8000:8000"
    container_name: django_container
    command:
      sh -c "ls; pip3 install -r requirements.txt; python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
