# Generated by Django 4.1.7 on 2023-04-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LM_API',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('API', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LM_Script',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('script', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
