version: "3.3"

#name: ai-text-detector

services:
  communicator:
    build:
      context: .
      dockerfile: communicator/Dockerfile
    command: sh -c "python3 ./communicator.py"
    environment:
      LISTEN_HOST: server
      LISTEN_PORT: 5555

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    command: sh -c "python3 ./server.py"
    container_name: server
    environment:
      SEND_HOST: server
      SEND_PORT: 5555
    ports:
      - '5555:5555'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    build: ./mysql
    ports:
      - "3306:3306"
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ai
    volumes:
      - my-datavolume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 1s
      timeout: 1s
      retries: 100

  api:
    build: ./django
    volumes:
      - ../:/DjangoProject
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /DjangoProject
    environment:
      SEND_HOST: server
      SEND_PORT: 5555
    ports:
      - "8000:8000"
      - "4004:8001"
    container_name: django_container
    command:
      sh -c "pip3 install -r requirements.txt; python manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    #  db:
    #    condition: service_healthy

volumes:
  my-datavolume: